name: Security Audit
on: [pull_request]
# on:
#   push:
#     paths: 
#       - '**/Cargo.toml'
#       - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: security-union/audit-check@6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cargo-lock-path: ./actix-api
      - uses: security-union/audit-check@7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cargo-lock-path: ./yew-ui
  